package com.example.demoapi.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class DauKy {
    String hangTonKho141; String
            nguyenGia151; String
            nguyenGia158; String
            xdcbdoDang210; String
            giaVonBanHang; String
            taiSanKhac211; String
            bdsdauTu154; String
            taiSanKhac213; String
            noPhaiTra300; String
            hangTonKho140; String
            coPhieuQuy414; String
            thueTNDNDaNop; String
            chiPhiKhac; String
            tienTonDauKy; String
            thuNhapKhac; String
            loiNhuanKhac; String
            tienMuaTSCD; String
            tienTonCuoiKy; String
            lcttuHDDT; String
            lnthuanTuHDKD; String
            chiPhiBanHang; String
            luuChuyenTienThuanTuHoatDongTaiChinh; String
            anhHuongThayDoiTyGiaHoiDoaiQuyDoiNgoaiTe; String
            tienThuHoiChoVayBanLaiCongCuNoDVK; String
            thuLaiTienChoVayCoTucVaLNDuocChia; String
            tienThuTuPhatHanhCPNhanVonGopCSH; String
            phaiThuCuaKhachHang131; String
            giaTriHaoMonLuyKe159; String
            nguoiMuaTraTienTruoc312; String
            vonChuSoHuu400; String
            vonDauTuCuaCSH411; String
            phaiTraNguoiBan311; String
            phaiThuKhac134; String
            thueVaCacKhoanPhaiNopNN313; String
            taiSanThieuChoXuLy135; String
            duPhongPhaiThuKhoDoi139; String
            giaTriHaoMonLuyKe152; String
            thueGTGTDuocKhauTru212; String
            tienVaCacKhoanTuongDuong110; String
            duPhongPhaiTra318; String
            dauTuTaiChinh111; String
            traTruocChoNguoiBan132; String
            chungKhoanKinhDoanh112; String
            dauTuGopVonVaoDVK121; String
            dauTuNamGiuDenNgayDaoHan120; String
            quyPhatTrienKHCN320; String
            taiSanCoDinh150; String
            tongConTaiSan200; String
            duPhongTonThatDTTC129; String
            phaiTraNguoiLaoDong314; String
            phaiTraKhac315; String
            vayVaNoThueTC316; String
            vonKinhDoanhDVTrucThuoc133; String
            phaiTraNoiBo317; String
            quyKhenThuongPhucLoi319; String
            cacKhoanPhaiThu130; String
            duPhongGiamGiaHTK149; String
            tongCongNguonVon500; String
            cacQuyThuocVonCSH416; String
            chiPhiLaiVay_KQKD; String
            cacKhoanDuPhong; String
            cacKhoanDieuChinhKhac; String
            thangDuVonCoPhan412; String
            lngopVeBanHangVaCungCapDV; String
            chenhLechTyGiaHoiDoai415; String
            loiNhuanTruocThue; String
            tangGiamHangTonKho; String
            chiPhiQuanLyDoanhNghiep; String
            tongLoiNhuanKeToanTruocThue; String
            loiNhuanSauThueTNDN; String
            loiNhuanSauThueCuaCongTyMe; String
            chiPhiLaiVay_GianTiep; String
            tangGiamCacKhoanPhaiThu; String
            tangGiamCacKhoanPhaiTra; String
            dtthuanVeBanHangVaCungCapDV; String
            tangGiamChiPhiTraTruoc; String
            khauHaoTaiSanCoDinh; String
            doanhThuHoatDongTaiChinh; String
            loiIchCuaCoDongKhongKiemSoat; String
            dieuChinhChoCacKhoan; String
            cacKhoanGiamTruDoanhThu; String
            laiCoBanTrenCoPhieu; String
            laiLoTuHoatDongDauTu; String
            laiLoCongTyLKLD; String
            doanhThuBanHangVaCungCapDV; String
            chiPhiHoatDongTaiChinh; String
            laiSuyGiamTrenCoPhieu; String
            chiPhiThueTNDNHienHanh; String
            chiPhiThueTNDNHoanLai; String
            vonKhacCuaCSH413; String
            coTucLoiNhuanTraChoCSH; String
            lctthuanTuHDTC; String
            anhHuongCuaThayDoiTyGia; String
            tienTraNoGocThueTC; String
            lctthuanTrongKy; String
            tienChiTraNoGocVay; String
            tienThuKhacTuHDKD; String
            thueThuNhapDoanhNghiepDaNop; String
            tienChiKhacChoHDKD; String
            tienLaiVayDaTra_LCTT_GianTiep; String
            tienVaTuongDuongTienCuoiKy; String
            thuTienBanHang; String
            coTucLoiNhuanDaTraChoChuSoHuu; String
            tienChiChoVayMuaCongCuNoDVK; String
            lctthuanTuHDKD; String
            tienChiTraNoThueTaiChinh; String
            tangGiamChungKhoanKinhDoanh; String
            tienTraChoNguoiCungCapHHDV; String
            tienTraChoNguoiLaoDong; String
            tienLaiVayDaTra_LCTT_TrucTiep; String
            tienChiTraVonGopChoCSH; String
            tienThuThanhLyNhuongBanTSCD; String
            tienVayNganHanDaiHanNhanDuoc; String
            tienChiDauTuGopVonVaoDVK; String
            tienThuHoiDauTuVonVaoDVK; String
            tienChiVonGopChoCSH; String
            tienTraNoGocVay; String
            tienThuTuDiVay; String
            luuChuyenTienThuanTrongKy; String
            tienVaTuongDuongTienDauKy; String
            loiNhuanTuHoatDongKinhDoanhTruocThayDoiVonLuuDong; String
            tienThuHoiDauTuGopVonVaoDonViKhac; String
            tienChiKhacChoHoatDongKinhDoanh; String
            tienThuTuThanhLyNhuongBanTSCDVaTSDaiHanKhac; String
            tienThuKhacTuHoatDongKinhDoanh; String
            luuChuyenTienThuanTuHoatDongDauTu; String
            tienThuTuPhatHanhCoPhieuNhanVonGopCuaChuSoHuu; String
            tienThuLaiChoVayCoTucVaLoiNhuanDuocChia; String
            loiNhuanSauThueChuaPhanPhoi417; String
            tienChiChoVayMuaCacCongCuNoCuaDonViKhac; String
            tienThuHoiChoVayBanLaiCacCongCuNoCuaDonViKhac; String
            luuChuyenTienThuanTuHoatDongKinhDoanh; String
            tienChiDeMuaSamXayDungTSCDVaTSDaiHanKhac; String
            tienChiDauTuGopVonVaoDonViKhac; String
            laiLoChenhLechTyGiaHoiDoaiChuaThucHien;

}
