package com.example.demoapi.controller;

import com.example.demoapi.model.Batch;
import com.example.demoapi.model.CuoiKy;
import com.example.demoapi.model.DauKy;
import com.example.demoapi.model.TT113;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/OCREcmAPI/services/BCTCService")
public class BTCTApiController {

    @PostMapping("/GetBCTC")
    public ResponseEntity<TT113> getDetail(@RequestHeader(value = "authorize") String value,
                                            @RequestBody Batch batch) {
        String auth = "IM80gqkhsVRloftQcJvajg==";
        String batchId = "3";

        TT113 tt113 = null;
        if (auth.equals(value) && batchId.equals(batch.getBatchID())) {
            tt113 = new TT113();
            DauKy dauKy = new DauKy();
            dauKy.setHangTonKho141(null);
            dauKy.setNguyenGia151(null);
            dauKy.setNguyenGia158(null);
            dauKy.setXdcbdoDang210(null);
            dauKy.setGiaVonBanHang(null);
            dauKy.setTaiSanKhac211(null);
            dauKy.setBdsdauTu154(null);
            dauKy.setTaiSanKhac213(null);
            dauKy.setNoPhaiTra300(null);
            dauKy.setHangTonKho140(null);
            dauKy.setCoPhieuQuy414(null);
            dauKy.setThueTNDNDaNop(null);
            dauKy.setChiPhiKhac(null);
            dauKy.setTienTonDauKy(null);
            dauKy.setThuNhapKhac(null);
            dauKy.setLoiNhuanKhac(null);
            dauKy.setTienMuaTSCD(null);
            dauKy.setTienTonCuoiKy(null);
            dauKy.setLcttuHDDT(null);
            dauKy.setLnthuanTuHDKD(null);
            dauKy.setChiPhiBanHang(null);
            dauKy.setLuuChuyenTienThuanTuHoatDongTaiChinh(null);
            dauKy.setAnhHuongThayDoiTyGiaHoiDoaiQuyDoiNgoaiTe(null);
            dauKy.setTienThuHoiChoVayBanLaiCongCuNoDVK(null);
            dauKy.setThuLaiTienChoVayCoTucVaLNDuocChia(null);
            dauKy.setTienThuTuPhatHanhCPNhanVonGopCSH(null);
            dauKy.setPhaiThuCuaKhachHang131(null);
            dauKy.setGiaTriHaoMonLuyKe159(null);
            dauKy.setNguoiMuaTraTienTruoc312(null);
            dauKy.setVonChuSoHuu400(null);
            dauKy.setVonDauTuCuaCSH411(null);
            dauKy.setPhaiTraNguoiBan311(null);
            dauKy.setPhaiThuKhac134(null);
            dauKy.setThueVaCacKhoanPhaiNopNN313(null);
            dauKy.setTaiSanThieuChoXuLy135(null);
            dauKy.setDuPhongPhaiThuKhoDoi139(null);
            dauKy.setGiaTriHaoMonLuyKe152(null);
            dauKy.setThueGTGTDuocKhauTru212(null);
            dauKy.setTienVaCacKhoanTuongDuong110(null);
            dauKy.setDuPhongPhaiTra318(null);
            dauKy.setDauTuTaiChinh111(null);
            dauKy.setTraTruocChoNguoiBan132(null);
            dauKy.setChungKhoanKinhDoanh112(null);
            dauKy.setDauTuGopVonVaoDVK121(null);
            dauKy.setDauTuNamGiuDenNgayDaoHan120(null);
            dauKy.setQuyPhatTrienKHCN320(null);
            dauKy.setTaiSanCoDinh150(null);
            dauKy.setTongConTaiSan200(null);
            dauKy.setDuPhongTonThatDTTC129(null);
            dauKy.setPhaiTraNguoiLaoDong314(null);
            dauKy.setPhaiTraKhac315(null);
            dauKy.setVayVaNoThueTC316(null);
            dauKy.setVonKinhDoanhDVTrucThuoc133(null);
            dauKy.setPhaiTraNoiBo317(null);
            dauKy.setQuyKhenThuongPhucLoi319(null);
            dauKy.setCacKhoanPhaiThu130(null);
            dauKy.setDuPhongGiamGiaHTK149(null);
            dauKy.setTongCongNguonVon500(null);
            dauKy.setCacQuyThuocVonCSH416(null);
            dauKy.setChiPhiLaiVay_KQKD(null);
            dauKy.setCacKhoanDuPhong(null);
            dauKy.setCacKhoanDieuChinhKhac(null);
            dauKy.setThangDuVonCoPhan412(null);
            dauKy.setLngopVeBanHangVaCungCapDV(null);
            dauKy.setChenhLechTyGiaHoiDoai415(null);
            dauKy.setLoiNhuanTruocThue(null);
            dauKy.setTangGiamHangTonKho(null);
            dauKy.setChiPhiQuanLyDoanhNghiep(null);
            dauKy.setTongLoiNhuanKeToanTruocThue(null);
            dauKy.setLoiNhuanSauThueTNDN(null);
            dauKy.setLoiNhuanSauThueCuaCongTyMe(null);
            dauKy.setChiPhiLaiVay_GianTiep(null);
            dauKy.setTangGiamCacKhoanPhaiThu(null);
            dauKy.setTangGiamCacKhoanPhaiTra(null);
            dauKy.setDtthuanVeBanHangVaCungCapDV(null);
            dauKy.setTangGiamChiPhiTraTruoc(null);
            dauKy.setKhauHaoTaiSanCoDinh(null);
            dauKy.setDoanhThuHoatDongTaiChinh(null);
            dauKy.setLoiIchCuaCoDongKhongKiemSoat(null);
            dauKy.setDieuChinhChoCacKhoan(null);
            dauKy.setCacKhoanGiamTruDoanhThu(null);
            dauKy.setLaiCoBanTrenCoPhieu(null);
            dauKy.setLaiLoTuHoatDongDauTu(null);
            dauKy.setLaiLoCongTyLKLD(null);
            dauKy.setDoanhThuBanHangVaCungCapDV(null);
            dauKy.setChiPhiHoatDongTaiChinh(null);
            dauKy.setLaiSuyGiamTrenCoPhieu(null);
            dauKy.setChiPhiThueTNDNHienHanh(null);
            dauKy.setChiPhiThueTNDNHoanLai(null);
            dauKy.setVonKhacCuaCSH413(null);
            dauKy.setCoTucLoiNhuanTraChoCSH(null);
            dauKy.setLctthuanTuHDTC(null);
            dauKy.setAnhHuongCuaThayDoiTyGia(null);
            dauKy.setTienTraNoGocThueTC(null);
            dauKy.setLctthuanTrongKy(null);
            dauKy.setTienChiTraNoGocVay(null);
            dauKy.setTienThuKhacTuHDKD(null);
            dauKy.setThueThuNhapDoanhNghiepDaNop(null);
            dauKy.setTienChiKhacChoHDKD(null);
            dauKy.setTienLaiVayDaTra_LCTT_GianTiep(null);
            dauKy.setTienVaTuongDuongTienCuoiKy(null);
            dauKy.setThuTienBanHang(null);
            dauKy.setCoTucLoiNhuanDaTraChoChuSoHuu(null);
            dauKy.setTienChiChoVayMuaCongCuNoDVK(null);
            dauKy.setLctthuanTuHDKD(null);
            dauKy.setTienChiTraNoThueTaiChinh(null);
            dauKy.setTangGiamChungKhoanKinhDoanh(null);
            dauKy.setTienTraChoNguoiCungCapHHDV(null);
            dauKy.setTienTraChoNguoiLaoDong(null);
            dauKy.setTienLaiVayDaTra_LCTT_TrucTiep(null);
            dauKy.setTienChiTraVonGopChoCSH(null);
            dauKy.setTienThuThanhLyNhuongBanTSCD(null);
            dauKy.setTienVayNganHanDaiHanNhanDuoc(null);
            dauKy.setTienChiDauTuGopVonVaoDVK(null);
            dauKy.setTienThuHoiDauTuVonVaoDVK(null);
            dauKy.setTienChiVonGopChoCSH(null);
            dauKy.setTienTraNoGocVay(null);
            dauKy.setTienThuTuDiVay(null);
            dauKy.setLuuChuyenTienThuanTrongKy(null);
            dauKy.setTienVaTuongDuongTienDauKy(null);
            dauKy.setLoiNhuanTuHoatDongKinhDoanhTruocThayDoiVonLuuDong(null);
            dauKy.setTienThuHoiDauTuGopVonVaoDonViKhac(null);
            dauKy.setTienChiKhacChoHoatDongKinhDoanh(null);
            dauKy.setTienThuTuThanhLyNhuongBanTSCDVaTSDaiHanKhac(null);
            dauKy.setTienThuKhacTuHoatDongKinhDoanh(null);
            dauKy.setLuuChuyenTienThuanTuHoatDongDauTu(null);
            dauKy.setTienThuTuPhatHanhCoPhieuNhanVonGopCuaChuSoHuu(null);
            dauKy.setTienThuLaiChoVayCoTucVaLoiNhuanDuocChia(null);
            dauKy.setLoiNhuanSauThueChuaPhanPhoi417(null);
            dauKy.setTienChiChoVayMuaCacCongCuNoCuaDonViKhac(null);
            dauKy.setTienThuHoiChoVayBanLaiCacCongCuNoCuaDonViKhac(null);
            dauKy.setLuuChuyenTienThuanTuHoatDongKinhDoanh(null);
            dauKy.setTienChiDeMuaSamXayDungTSCDVaTSDaiHanKhac(null);
            dauKy.setTienChiDauTuGopVonVaoDonViKhac(null);
            dauKy.setLaiLoChenhLechTyGiaHoiDoaiChuaThucHien(null);
            tt113.setDauKy(dauKy);
            tt113.setCode("00");

            Batch batch1 = new Batch();
            batch1.setBatchID("3");
            batch1.setBieuMauBCTC("TT133");
            batch1.setLoaiBCTC("Thuế");
            batch1.setDonViTinh("Đồng");
            batch1.setNguonDuLieu("Bên thứ 3 cung cấp");
            batch1.setNamBCTC("2019");
            tt113.setBatch(batch1);

            CuoiKy cuoiKy = new CuoiKy();
            cuoiKy.setThuNhapKhac_(200000.0);
            cuoiKy.setChiPhiKhac_(0.0);
            cuoiKy.setBdsdauTu154_(-11);
            cuoiKy.setNguyenGia158_(11);
            cuoiKy.setNoPhaiTra300_(11);
            cuoiKy.setNguyenGia151_(11);
            cuoiKy.setTienTonDauKy_(11);
            cuoiKy.setTienMuaTSCD_(11);
            cuoiKy.setLcttuHDDT_(11);
            cuoiKy.setLoiNhuanKhac_(11);
            cuoiKy.setDauTuTaiChinh111_(11);
            cuoiKy.setGiaTriHaoMonLuyKe159_(11);
            cuoiKy.setPhaiTraNoiBo317_(11);
            cuoiKy.setVayVaNoThueTC316_(11);
            cuoiKy.setDuPhongPhaiTra318_(11);
            cuoiKy.setTaiSanCoDinh150_(11);
            cuoiKy.setDuPhongPhaiThuKhoDoi139_(11);
            cuoiKy.setHangTonKho141_(11);
            cuoiKy.setXdcbdoDang210_(11);
            cuoiKy.setDauTuNamGiuDenNgayDaoHan120_(11);
            cuoiKy.setDauTuGopVonVaoDVK121_(11);
            cuoiKy.setThueGTGTDuocKhauTru212_(11);
            cuoiKy.setVonDauTuCuaCSH411_(11);
            cuoiKy.setThangDuVonCoPhan412_(11);
            cuoiKy.setTraTruocChoNguoiBan132_(11);
            cuoiKy.setNguoiMuaTraTienTruoc312_(11);
            cuoiKy.setTienVaCacKhoanTuongDuong110_(11);
            cuoiKy.setTaiSanThieuChoXuLy135_(11);
            cuoiKy.setPhaiTraNguoiBan311_(11);
            cuoiKy.setDuPhongGiamGiaHTK149_(11);
            cuoiKy.setTaiSanKhac211_(11);
            cuoiKy.setVonKinhDoanhDVTrucThuoc133_(11);
            cuoiKy.setHangTonKho140_(11);
            cuoiKy.setThueVaCacKhoanPhaiNopNN313_(11);
            cuoiKy.setDuPhongTonThatDTTC129_(11);
            cuoiKy.setPhaiThuCuaKhachHang131_(11);
            cuoiKy.setChungKhoanKinhDoanh112_(11);
            cuoiKy.setPhaiTraNguoiLaoDong314_(11);
            cuoiKy.setTaiSanKhac213_(11);
            cuoiKy.setPhaiTraKhac315_(11);
            cuoiKy.setQuyKhenThuongPhucLoi319_(11);
            cuoiKy.setQuyPhatTrienKHCN320_(11);
            cuoiKy.setVonChuSoHuu400_(11);
            cuoiKy.setTongConTaiSan200_(11);
            cuoiKy.setPhaiThuKhac134_(11);
            cuoiKy.setGiaTriHaoMonLuyKe152_(11);
            cuoiKy.setCacKhoanPhaiThu130_(11);
            cuoiKy.setChenhLechTyGiaHoiDoai415_(11);
            cuoiKy.setChiPhiThueTNDNHienHanh_(11);
            cuoiKy.setChiPhiHoatDongTaiChinh_(11);
            cuoiKy.setDtthuanVeBanHangVaCungCapDV_(11);
            cuoiKy.setGiaVonBanhang_(11);
            cuoiKy.setChiPhiLaiVay_LCTT_GianTiep_(11);
            cuoiKy.setCoPhieuQuy414_(11);
            cuoiKy.setCacKhoanDieuChinhKhac_(11);
            cuoiKy.setTangGiamHangTonKho_(11);
            cuoiKy.setCacKhoanDuPhong_(11);
            cuoiKy.setTangGiamCacKhoanPhaiThu_(11);
            cuoiKy.setTangGiamCacKhoanPhaiTra_(11);
            cuoiKy.setChiPhiThueTNDNHoanLai_(11);
            cuoiKy.setLoiIchCuaCoDongKhongKiemSoat_(11);
            cuoiKy.setLoiNhuanSauThueTNDN_(11);
            cuoiKy.setLnthuanTuHDKD_(11);
            cuoiKy.setLoiNhuanTruocThue_(11);
            cuoiKy.setLaiSuyGiamTrenCoPhieu_(11);
            cuoiKy.setCacKhoanGiamTruDoanhThu_(11);
            cuoiKy.setChiPhiQuanLyDoanhNghiep_(11);
            cuoiKy.setLoiNhuanSauThueCuaCongTyMe_(11);
            cuoiKy.setLngopVeBanHangVaCungCapDV_(11);
            cuoiKy.setCacQuyThuocVonCSH416_(11);
            cuoiKy.setVonKhacCuaCSH413_(11);
            cuoiKy.setTongLoiNhuanKeToanTruocThue_(11);
            cuoiKy.setLaiCoBanTrenCoPhieu_(11);
            cuoiKy.setDoanhThuBanHangVaCungCapDV_(11);
            cuoiKy.setDieuChinhChoCacKhoan_(11);
            cuoiKy.setChiPhiLaiVay_KQKD_(11);
            cuoiKy.setKhauHaoTaiSanCoDinh_(11);
            cuoiKy.setLaiLoTuHoatDongDauTu_(11);
            cuoiKy.setTongCongNguonVon500_(11);
            cuoiKy.setDoanhThuHoatDongTaiChinh_(11);
            cuoiKy.setChiPhiBanHang_(11);
            cuoiKy.setLaiLoCongTyLKLD_(11);
            cuoiKy.setThueTNDNDaNop_(11);
            cuoiKy.setLctthuanTuHDKD_(11);
            cuoiKy.setAnhHuongCuaThayDoiTyGia_(11);
            cuoiKy.setTienChiDauTuGopVonVaoDVK_(11);
            cuoiKy.setTienVaTuongDuongTienDauKy_(11);
            cuoiKy.setTangGiamChungKhoanKinhDoanh_(11);
            cuoiKy.setTangGiamChiPhiTraTruoc_(11);
            cuoiKy.setTienVaTuongDuongTienCuoiKy_(11);
            cuoiKy.setTienThuHoiDauTuVonVaoDVK_(11);
            cuoiKy.setTienChiVonGopChoCSH_(11);
            cuoiKy.setThueThuNhapDoanhNghiepDaNop_(11);
            cuoiKy.setTienThuTuDiVay_(11);
            cuoiKy.setTienTraChoNguoiCungCapHHDV_(11);
            cuoiKy.setTienTraNoGocVay_(11);
            cuoiKy.setTienTraNoGocThueTC_(11);
            cuoiKy.setLctthuanTuHDTC_(11);
            cuoiKy.setTienTonCuoiKy_(11);
            cuoiKy.setTienChiTraNoThueTaiChinh_(11);
            cuoiKy.setTienTraChoNguoiLaoDong_(11);
            cuoiKy.setTienChiTraNoGocVay_(11);
            cuoiKy.setTienChiKhacChoHDKD_(11);
            cuoiKy.setTienThuThanhLyNhuongBanTSCD_(11);
            cuoiKy.setTienChiChoVayMuaCongCuNoDVK_(11);
            cuoiKy.setThuTienBanHang_(11);
            cuoiKy.setCoTucLoiNhuanTraChoCSH_(11);
            cuoiKy.setTienThuKhacTuHDKD_(11);
            cuoiKy.setLctthuanTrongKy_(11);
            cuoiKy.setTienChiTraVonGopChoCSH_(11);
            cuoiKy.setLuuChuyenTienThuanTrongKy_(11);
            cuoiKy.setTienVayNganHanDaiHanNhanDuoc_(11);
            cuoiKy.setLoiNhuanSauThueChuaPhanPhoi417_(11);
            cuoiKy.setTienThuKhacTuHoatDongKinhDoanh_(11);
            cuoiKy.setTienChiKhacChoHoatDongKinhDoanh_(11);
            cuoiKy.setLuuChuyenTienThuanTuHoatDongKinhDoanh_(11);
            cuoiKy.setLaiLoChenhLechTyGiaHoiDoaiChuaThucHien_(11);
            cuoiKy.setTienThuTuThanhLyNhuongBanTSCDVaTSDaiHanKhac_(11);
            cuoiKy.setTienLaiVayDaTra_LCTT_GianTiep_(11);
            cuoiKy.setLoiNhuanTuHoatDongKinhDoanhTruocThayDoiVLD_(11);
            cuoiKy.setTienChiDeMuaSamXayDungTSCDVaTSDaiHanKhac_(11);
            cuoiKy.setTienChiChoVayMuaCacCongCuNoCuaDonViKhac_(11);
            cuoiKy.setTienThuLaiChoVayCoTucVaLoiNhuanDuocChia_(11);
            cuoiKy.setTienThuTuPhatHanhCoPhieuNhanVonGopCuaCSH_(11);
            cuoiKy.setLuuChuyenTienThuanTuHoatDongTaiChinh_(11);
            cuoiKy.setTienLaiVayDaTra_LCTT_TrucTiep_(11);
            cuoiKy.setTienThuHoiChoVayBanLaiCongCuNoDVK_(11);
            cuoiKy.setTienChiDauTuGopVonVaoDonViKhac_(11);
            cuoiKy.setThuLaiTienChoVayCoTucVaLNDuocChia_(11);
            cuoiKy.setTienThuHoiChoVayBanLaiCacCongCuNoCuaDVK_(11);
            cuoiKy.setCoTucLoiNhuanDaTraChoChuSoHuu_(11);
            cuoiKy.setTienThuHoiDauTuGopVonVaoDonViKhac_(11);
            cuoiKy.setAnhHuongThayDoiTyGiaHoiDoaiQuyDoiNgoaiTe_(11);
            cuoiKy.setLuuChuyenTienThuanTuHoatDongDauTu_(11);
            cuoiKy.setTienThuTuPhatHanhCPNhanVonGopCSH_(123555.0);
            tt113.setCuoiKy(cuoiKy);
            return new ResponseEntity<>(tt113, HttpStatus.OK);
        } else {
            System.out.println("sai");
            TT113 tt1131 = new TT113();
            return new ResponseEntity<>(tt1131, HttpStatus.OK);
        }


    }
}
